export const industries = [
    "Technology",
    "Finance",
    "Healthcare",
    "Education",
    "Construction",
    "Manufacturing",
    "Retail",
    "Other",
    "Jamovi",
    ".NET",
    "3ds Max",
    "Ableton Live",
    "Accounting",
    "Acting Audition",
    "Acting technique",
    "Adobe After Effects",
    "Adobe Audition",
    "Adobe Creative Suite",
    "Adobe Dreamweaver",
    "Adobe Fireworks",
    "Adobe Flash",
    "Adobe Illustrator",
    "Adobe Indesign",
    "Adobe Photoshop",
    "Adobe Photoshop Lightroom CC",
    "Adobe Premiere Pro",
    "Adobe XD",
    "Advanced Excel",
    "AJAX",
    "Algorithms",
    "Allegro Software",
    "Amazon Web Server (AWS)",
    "Amazon Web Services (AWS)",
    "American English",
    "Analog And Digital Circuits",
    "Anchoring",
    "Android",
    "Angular 2.0",
    "Angular 7.0",
    "AngularJS",
    "Animation",
    "ANSA",
    "Ansible",
    "ANSYS",
    "Apache",
    "Apache Cassandra",
    "Apache CloudStack",
    "Apache Kafka",
    "Apex",
    "APIs",
    "Arabic Proficiency (Spoken)",
    "Arabic Proficiency (Written)",
    "ArcGIS",
    "Arduino",
    "ARM Microcontroller",
    "Articulate 360",
    "Articulate Storyline",
    "Artificial intelligence",
    "ASP.NET",
    "Assamese Proficiency (Spoken)",
    "Assamese Proficiency (Written)",
    "Atmel AVR",
    "Audacity",
    "Audio Editing",
    "Audio Making",
    "Audiology",
    "AutoCAD",
    "Autodesk 123D design",
    "Autodesk Alias",
    "Autodesk CFD",
    "Autodesk Fusion 360",
    "Autodesk Inventor",
    "Autodesk Maya",
    "Autodesk Moldflow",
    "Autodesk Mudbox",
    "Autodesk Revit",
    "Autodesk SketchBook",
    "Backbone.js",
    "Bar bending schedule/Schedule of bars",
    "Bash",
    "Battery Management Systems",
    "Battery Pack Testing",
    "Bengali Proficiency (Spoken)",
    "Bengali Proficiency (Written)",
    "Big Data Analytics",
    "BIM (Building Information Modeling)",
    "Bioinformatics",
    "Biology",
    "Biostatistics",
    "Blender 3D",
    "Blockchain",
    "Blogging",
    "BMS modelling & simulation",
    "Bodo Proficiency(Spoken)",
    "Bodo Proficiency(Written)",
    "Bootstrap",
    "British English",
    "Bubble.io",
    "Business Analysis",
    "Business Research",
    "C Programming",
    "C#",
    "C#.NET",
    "C++ Programming",
    "CAD",
    "CakePHP",
    "Calligraphy",
    "CAM",
    "Canva",
    "Catalyst MVC Web Framework",
    "Catia",
    "CCNA",
    "Chemistry",
    "CI/CD",
    "Cinema 4D",
    "Circuit Design",
    "Circuit Modeling & Simulation",
    "Client interaction",
    "Client Relationship",
    "Clip Studio Paint",
    "CLO3D",
    "Cloud Computing",
    "Cloud Firestore",
    "CMS",
    "CNC",
    "CNC Programming",
    "CodeIgniter",
    "Colour Theory for Designers",
    "Compensation management",
    "Computational Neuroscience",
    "Computer Networking",
    "Computer Networks",
    "Computer Vision",
    "COMSOL",
    "Content Marketing",
    "Content Writing",
    "CONVERGE",
    "Copywriting",
    "CorelDRAW",
    "Creative Writing",
    "CRM",
    "CSS",
    "Culinary Arts",
    "Cybersecurity",
    "Dancer MVC Web Framework",
    "Dart",
    "Data Analysis",
    "Data Analytics",
  ];
  